// frontend/src/pages/legal/TermsOfService.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { FaLeaf, FaArrowLeft } from 'react-icons/fa';

const Section = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="text-lg font-semibold text-white mb-3">{title}</h2>
    <div className="text-sm text-emerald-100/60 leading-relaxed space-y-3">
      {children}
    </div>
  </div>
);

const TermsOfService = () => {
  const lastUpdated = 'January 2026';

  return (
    <div className="min-h-screen bg-[#071021] px-4 py-10">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-8">
          <div className="relative inline-block">
            <div className="absolute inset-0 bg-emerald-500/30 rounded-full blur-2xl"></div>
            <FaLeaf className="text-4xl text-emerald-400 mx-auto mb-3 relative" />
          </div>
          <h1 className="text-2xl font-bold text-white">
            Code<span className="text-emerald-400">Carbon</span> AI — CarbonWise
          </h1>
        </div>

        <div className="bg-[#0F172A]/85 backdrop-blur-[20px] border border-emerald-500/15 rounded-3xl p-8 sm:p-10 shadow-2xl shadow-emerald-500/5">
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-emerald-300/40 text-sm mb-8">Last updated: {lastUpdated}</p>

          <Section title="1. Acceptance of Terms">
            <p>
              By creating an account or using CarbonWise, you agree to these Terms of Service. CarbonWise
              is a final-year academic project built to demonstrate sustainable software engineering
              concepts, and is not offered as a commercial production service.
            </p>
          </Section>

          <Section title="2. Use of the Platform">
            <p>You agree to use CarbonWise only for its intended purpose: analyzing repository</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>sustainability metrics for public or your own connected repositories</li>
              <li>reviewing AI-generated recommendations for educational purposes</li>
              <li>generating and reviewing sustainability reports</li>
            </ul>
            <p>You agree not to use the platform to attempt unauthorized access to other users' data or accounts.</p>
          </Section>

          <Section title="3. GitHub Account Connection">
            <p>
              Connecting your GitHub account is optional and used solely to analyze repositories you have
              access to, including private repositories if you grant that permission. You may disconnect
              your GitHub account at any time from Settings.
            </p>
          </Section>

          <Section title="4. AI-Generated Content">
            <p>
              Sustainability suggestions are generated by a third-party AI model based on real analysis
              data. These suggestions are estimates and recommendations only — they are not guaranteed to
              be complete, accurate, or suitable for production decision-making without independent review.
            </p>
          </Section>

          <Section title="5. Carbon & Sustainability Estimates">
            <p>
              Carbon footprint scores, energy consumption figures, and sustainability ratings shown on
              this platform are estimates derived from published methodology and coefficients (such as
              CI/CD compute time, repository size, and dependency count). They are intended for awareness
              and educational comparison, not as precise, audit-grade emissions measurements.
            </p>
          </Section>

          <Section title="6. Account Responsibility">
            <p>
              You are responsible for maintaining the confidentiality of your account credentials. Notify
              us if you suspect unauthorized access to your account.
            </p>
          </Section>

          <Section title="7. Availability">
            <p>
              As an academic project, CarbonWise is provided "as is" without uptime guarantees or formal
              support commitments.
            </p>
          </Section>

          <Section title="8. Changes to These Terms">
            <p>
              These terms may be updated as the project evolves. Continued use of the platform after
              changes constitutes acceptance of the revised terms.
            </p>
          </Section>

          <Link
            to="/register"
            className="inline-flex items-center gap-2 text-emerald-400 hover:text-emerald-300 font-medium text-sm transition-colors duration-200 mt-4"
          >
            <FaArrowLeft size={12} /> Back to Register
          </Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
